name: taller pipeline DevOps CI/CD
#Configurar Disparador (on:)
on:
  #tipo push cuando hagamos un push directo a una rama
  push:
    #POnemos las ramas ejemplos [rama1,rama2,rama3,etc..]
    branches: [main]
  
  #tipo 2 pull request, establezco que mi pipeline solo se ejecutre cuando haya un pull en main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

#COnfiguraciones de (Jobs:)
jobs:
  #Nombre del job, taller
  taller:
    #Sobre donde se va a ejecutar el job
    runs-on: ubuntu-20.04
    # Creando steps
    steps:
      - name: Descargar ultimo cambio de rama
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      #- name: Visualizar los cambios
      #  run: ls -l
      - name: Instalacion y Configuracion de jdk11
      # sacando java desde el marketplace de github/actions
        uses: actions/setup-java@v3
          #Parametros para la instalacion
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          server-id: github
          #Dando conexto de en donde va a trabajar Java
          settings-path: ${{github.workspaces}}
      #Vamos a ejecutar el test de la aplicacion
      - name: Ejecucion de Test
        run: mvn -B test --f pom.xml
      # Ahora el artefacto
      - name: Generar artefacto
        run: mvn -B package -DskipTests --f pom.xml